<?php

// This file is automatically generated and modified  

$CONF['sql_user']="root";
$CONF['sql_passwd']="123456";
$CONF['sql_host']="192.168.1.125";
$CONF['sql_db']="ago";
$CONF['ftp_use']="0";
$CONF['allow_dir_backup']="0";
$CONF['email_use']="0";
$CONF['sitename']="RHEF";
$CONF['lang']="espanol";
$CONF['import_error']="1";
$CONF['no_login']="1";
$CONF['login']="0";
$CONF['dir_backup']="0";
$CONF['dir_rec']="0";
$CONF['email']="";
$CONF['ftp_pasv']="1";
$CONF['ftp_del']="1";
$CONF['ftp_server']="example.net";
$CONF['ftp_user']="";
$CONF['ftp_passwd']="";
$CONF['ftp_path']="example/";
$CONF['ftp_port']="21";
$CONF['date']="%x %X";
$CONF['del_time']="99999999999";
$CONF['del_number']="50";
$CONF['timelimit']="900000";
$CONF['confirm']="1";
$CONF['stylesheet']="standard";

$PMBP_SYS_VAR['last_scheduled']="";
$PMBP_SYS_VAR['this_login']="";
$PMBP_SYS_VAR['last_login']="";
$PMBP_SYS_VAR['dir_lists']="1";
$PMBP_SYS_VAR['memory_limit']="3800000000";
$PMBP_SYS_VAR['except_tables']="";
$PMBP_SYS_VAR['scheduled_debug']="0";
$PMBP_SYS_VAR['schedule_all_dbs']="0";
$PMBP_SYS_VAR['ftp_timeout']="10";
$PMBP_SYS_VAR['dir_email_backup']="0";
$PMBP_SYS_VAR['F_dbs']="ago";
$PMBP_SYS_VAR['F_comment']="";
$PMBP_SYS_VAR['F_tables']="on";
$PMBP_SYS_VAR['F_data']="on";
$PMBP_SYS_VAR['F_drop']="on";
$PMBP_SYS_VAR['F_compression']="";
$PMBP_SYS_VAR['F_ftp_dirs']="";
$PMBP_SYS_VAR['F_ftp_dirs_2']="";
$PMBP_SYS_VAR['F_packed']="";
$PMBP_SYS_VAR['F_updates']="1";
$PMBP_SYS_VAR['F_ffadd']="1";
$PMBP_SYS_VAR['EXS_scheduled_file']="bb.php";
$PMBP_SYS_VAR['EXS_scheduled_dir']="../xp/planillas/";
$PMBP_SYS_VAR['EXS_period']="/24";
$PMBP_SYS_VAR['security_key']="f1fee1d9766c1fd4d2710c705257ec2b";

?>